/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 inimi.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/inimi.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.wallpanel_kiri.geometry} material={materials['wl-1007']} position={[-1.603, 1.519, -1.484]} rotation={[0, 0, -Math.PI]} scale={[1, 1.521, 1]} />
      <mesh geometry={nodes.uv.geometry} material={materials['Material.010']} position={[0.551, 1.499, -1.502]} rotation={[0, 0, -Math.PI / 2]} scale={[0.763, 0.499, 0.319]} />
      <mesh geometry={nodes.plafon_flat.geometry} material={materials['Material.006']} position={[-0.136, 3.747, 0.008]} />
      <group position={[-0.16, 3.159, 0.008]} scale={1.009}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['NP - 042NG']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['NP - 041NG']} />
      </group>
      <mesh geometry={nodes.lantai.geometry} material={materials['Material.005']} position={[-0.161, -0.001, 0.018]} scale={[1.522, 0.017, 1.522]} />
      <mesh geometry={nodes.dinding_depan.geometry} material={nodes.dinding_depan.material} position={[-0.161, 1.519, -1.502]} rotation={[Math.PI / 2, 0, 0]} scale={[1.522, 0.017, 1.522]} />
      <mesh geometry={nodes.dinding_kanan.geometry} material={nodes.dinding_kanan.material} position={[1.359, 1.519, 0.018]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.522, 0.017, 1.522]} />
      <mesh geometry={nodes.wallpanel_kiri001.geometry} material={materials['Material.005']} position={[1.341, 1.519, -1.406]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[1, 1.521, 1]} />
      <group position={[0, 1.604, 2.834]} scale={0.138}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['wl-1019']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['wl-1017']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['wl-1015']} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials['wl-1014']} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials['wl-1013']} />
        <mesh geometry={nodes.Cube001_6.geometry} material={materials['wl-1010']} />
        <mesh geometry={nodes.Cube001_7.geometry} material={materials['wl-1007']} />
        <mesh geometry={nodes.Cube001_8.geometry} material={materials['NP - 004']} />
        <mesh geometry={nodes.Cube001_9.geometry} material={materials['NP - 008']} />
        <mesh geometry={nodes.Cube001_10.geometry} material={materials['NP - 029']} />
        <mesh geometry={nodes.Cube001_11.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube001_12.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube001_13.geometry} material={materials['wl-1020']} />
      </group>
      <group position={[0.307, 0.619, -1.241]} scale={[1, 1, 1.513]}>
        <mesh geometry={nodes.Cube007.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials['wl-1020.002']} />
      </group>
      <group position={[-0.157, 0.527, -1.265]} scale={[1.526, 0.236, 0.211]}>
        <mesh geometry={nodes.Cube012.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['Material.007']} />
      </group>
      <mesh geometry={nodes.wallboard.geometry} material={materials['Material.009']} position={[-0.161, 1.521, 0.018]} scale={[1.522, 1.52, 0.006]} />
      <mesh geometry={nodes.partisi_tv.geometry} material={materials['Material.012']} position={[-0.161, 2.393, -1.281]} scale={[1.522, 0.017, 0.19]} />
    </group>
  )
}

useGLTF.preload('/inimi.glb')
